  spring:
    application:
      name: "configserver"
    profiles:
      # active: native # In classpath or in file system
      active: git
    cloud:
      config:
        server:
          # native:
            # search-locations: "classpath:/config"  # Store configserver in the classpath (access local file yml)
            # search-locations: "file:///D://Users//bahma//OneDrive//Documents//FORMATIONS//Udemy-formation//microservices_v2-config" # Store configserver in the file system (access file yml into this path)
          git:
            uri: "https://github.com/mamadou4bah/Microservices_V2-config.git" #Store configserver in the github repositories
            default-label: main # default branch that you want to access in the github reposiotries
            timeout: 5
            clone-on-start: true
            force-pull: true
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
    endpoint:
      health:
        probes:
          enabled: true
    metrics:
      tags:
        application: ${spring.application.name}

  encrypt:
    key: "CBFB76CF197EFA6F86672F26B4753" # https://randomkeygen.com/  (256-bit WEP Keys)
    #key: "45D81EC1EF61DF9AD8D3E5BB397F9"

  server:
    port: 8071

  logging:
    pattern:
      level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
