# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: mamadou4bah/cards
  tag: s14

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

mysql:
  url: jdbc:mysql://cardsdb-service:3308/cardsdb
  username: root
  password: root

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
database_mysql_enabled: true