build:
  version: "1.0"

cards:
  message: "Welcome to mamadou4bah cards related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@bmwas-consulting.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721