apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: mamadou4bah/accounts:s12
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: mbabank-configmap
              key: ACCOUNTS_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: mbabank-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: mbabank-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: mbabank-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        # Variables d'environnement pour la connexion à la base de données MySQL
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://accountsdb-service:3306/accountsdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root  # Assurez-vous que cela correspond à votre utilisateur MySQL
        - name: SPRING_DATASOURCE_PASSWORD
          value: root  # Assurez-vous que cela correspond à votre mot de passe MySQL
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
