apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
  labels:
    app: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
      - name: loans
        image: mamadou4bah/loans:s12
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: mbabank-configmap
              key: LOANS_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: mbabank-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: mbabank-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: mbabank-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        # Variables d'environnement pour la connexion à la base de données MySQL
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://loansdb-service:3307/loansdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root  # Assurez-vous que cela correspond à votre utilisateur MySQL
        - name: SPRING_DATASOURCE_PASSWORD
          value: root  # Assurez-vous que cela correspond à votre mot de passe MySQL
---
apiVersion: v1
kind: Service
metadata:
  name: loans
spec:
  selector:
    app: loans
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
