apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
  labels:
    app: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
      - name: cards
        image: mamadou4bah/cards:s12
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: mbabank-configmap
              key: CARDS_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: mbabank-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: mbabank-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: mbabank-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        # Variables d'environnement pour la connexion à la base de données MySQL
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://cardsdb-service:3308/cardsdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root  # Assurez-vous que cela correspond à votre utilisateur MySQL
        - name: SPRING_DATASOURCE_PASSWORD
          value: root  # Assurez-vous que cela correspond à votre mot de passe MySQL
---
apiVersion: v1
kind: Service
metadata:
  name: cards
spec:
  selector:
    app: cards
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
