apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loansdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-loansdb
  labels:
    app: loansdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loansdb
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
        - name: loansdb
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root           # Changez cela par un mot de passe sécurisé
            - name: MYSQL_DATABASE
              value: loansdb     # Changez cela par le nom de votre base de données
          ports:
            - containerPort: 3307
          volumeMounts:
            - name: loansdb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: loansdb-storage
          persistentVolumeClaim:
            claimName: loansdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: loansdb-service
  labels:
    app: loansdb
spec:
  ports:
    - port: 3307
      targetPort: 3307
  selector:
    app: loansdb
  type: ClusterIP