apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardsdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-cardsdb
  labels:
    app: cardsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardsdb
  template:
    metadata:
      labels:
        app: cardsdb
    spec:
      containers:
        - name: cardsdb
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root           # Changez cela par un mot de passe sécurisé
            - name: MYSQL_DATABASE
              value: cardsdb     # Changez cela par le nom de votre base de données
          ports:
            - containerPort: 3308
          volumeMounts:
            - name: cardsdb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: cardsdb-storage
          persistentVolumeClaim:
            claimName: cardsdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cardsdb-service
  labels:
    app: cardsdb
spec:
  ports:
    - port: 3308
      targetPort: 3308
  selector:
    app: cardsdb
  type: ClusterIP