apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accountsdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-accountsdb
  labels:
    app: accountsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountsdb
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
        - name: accountsdb
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root           # Changez cela par un mot de passe sécurisé
            - name: MYSQL_DATABASE
              value: accountsdb     # Changez cela par le nom de votre base de données
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: accountsdb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: accountsdb-storage
          persistentVolumeClaim:
            claimName: accountsdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: accountsdb-service
  labels:
    app: accountsdb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: accountsdb
  type: ClusterIP